services:
  activemq:
    image: apache/activemq-classic:6.1.4
    ports:
      - "61616:61616"  # ActiveMQ port
      - "8161:8161"    # Web console
    volumes:
      - activemq_data:/opt/activemq/data
    environment:
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin
    networks:
      - pitrac_net
  tomee:
    build:
      context: .
    ports:
      - "8080:8080"    # TomEE port (host:container)
    volumes:
      - images_share:/app/LM_Shares/Images
      - web_share:/app/LM_Shares/WebShare
    environment:
      - PITRAC_MSG_BROKER_FULL_ADDRESS=tcp://activemq:61616
    depends_on:
      - activemq
    networks:
      - pitrac_net

volumes:
  activemq_data:
  images_share:
  web_share:

networks:
  pitrac_net:
    driver: bridge
