cmake_minimum_required(VERSION 3.28)

project(Utils)

# Add subdirectories for each utility
add_subdirectory(ColorSys)
add_subdirectory(CVUtils)
add_subdirectory(Detection)
add_subdirectory(Logging)
add_subdirectory(FileUtils)
add_subdirectory(Json)
add_subdirectory(Calibration)
add_subdirectory(CameraUtils)
add_subdirectory(I2CUtils)
